apiVersion: v1
kind: Service
metadata:
  labels:
    product: ols
    project: {{ .Values.PROJECT }}
    component: solr-service
    deployment-id:  {{ .Release.Name }}
  name: {{ .Release.Name }}-solr-service
spec:
  ports:
  - name: "8983"
    port: 8983
    targetPort: 8983
  selector:
    product: ols
    project: {{ .Values.PROJECT }}
    component: solr-service
    deployment-id:  {{ .Release.Name }}
