apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ols-neo4j-data
  name: {{ .Release.Name }}-neo4j-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-ceph-block-hdd
