version: '3.8'

networks:
    clint:

volumes:
  neo4j-import:
  neo4j-plugins:

services:
    triplestore:
        build: ./3-data-RDF-conversion/Triplestore/secoresearch-fuseki/
        restart: always
        container_name: triplestore
        environment:
            QUERY_TIMEOUT: "360000"
            USERNAME: "admin"
            ADMIN_PASSWORD: "pw123"
        ports:
            - "3030:3030"
        networks:
            - clint

    neo4j:
        image: neo4j:4.4.19-community
        restart: always
        container_name: neo4j
        environment:
            NEO4J_AUTH: "neo4j/neo4jpwd"
            NEO4JLABS_PLUGINS: '["apoc", "n10s"]'
        ports:
            - "7474:7474"
            - "7687:7687"
        networks:
            - clint
        volumes:
            # - ./neo4j.conf:/conf/neo4j.conf
            # - ./data:/var/lib/neo4j/data
            # - ./logs:/var/lib/neo4j/logs
            # - ./conf:/var/lib/neo4j/conf
            - neo4j-import:/import
            - neo4j-plugins:/plugins

    api:
        build: ./7-knowledge-graph-ETL/Import-API/api/
        restart: always
        container_name: api
        ports:
            - "8000:8000"
        environment:
            TS_HOST: "triplestore:3030"
            # Must match triplestore credentials
            TS_USER: "admin"
            TS_PWD: "pw123"

            # Must match neo4j credentials
            NEO4J_HOST: "neo4j:7687"
            NEO4J_DB_USER: "neo4j"
            NEO4J_DB_PWD: "neo4jpwd"
        networks:
            - clint
        volumes:
            - neo4j-import:/upload/
