apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sam-terminology-data
  name: {{ .Release.Name }}-terminology-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block-hdd
