# Copyright 2023 Fraunhofer Institute SCAI, St. Augustin, Germany
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webofclint-deployment
spec:
  selector:
    matchLabels:
      component: webofclint-deployment
      version: {{ .Chart.AppVersion }}
      deployment-id:  {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        component: webofclint-deployment
        version: {{ .Chart.AppVersion }}
        deployment-id:  {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: api
          image: docker.arty.scai.fraunhofer.de/who-etl-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: K8S
              value: "true"
            - name: TS_USER
              valueFrom:
                secretKeyRef:
                  name: webofclint-secret
                  key: fuseki-username
            - name: TS_PWD
              valueFrom:
                secretKeyRef:
                  name: webofclint-secret
                  key: fuseki-pwd

        - name: neo4j
          image: neo4j:4.4.19-community
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: api
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4JLABS_PLUGINS
              value: '["apoc", "n10s"]'
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: webofclint-secret
                  key: neo4j
          volumeMounts:
            - mountPath: /var/lib/neo4j/data
              name: neo4j-data

        - name: secoresearch-fuseki
          image: docker.example.com/secoresearch-fuseki:latest
          env:
          - name: QUERY_TIMEOUT
            value: "360000"
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: webofclint-secret
                key: fuseki-pwd
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: webofclint-secret
                key: fuseki-username
          imagePullPolicy: Always
          ports:
            - name: secoresearch
              containerPort: 3030
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /fuseki-base/databases
              name: secoresearch-fuseki-data
              subPath: databases
            - mountPath: /fuseki-base/configuration
              name: secoresearch-fuseki-data
              subPath: configuration
            - mountPath: /fuseki-base/staging
              name: secoresearch-fuseki-data
              subPath: staging
            - mountPath: /fuseki-base/backups
              name: secoresearch-fuseki-data
              subPath: backups
      restartPolicy: Always

      volumes:
        - name: secoresearch-fuseki-data
          persistentVolumeClaim:
            claimName: secoresearch-fuseki-data
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data