apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: secoresearch-fuseki-data
  name: secoresearch-fuseki-data
spec:
  storageClassName: rook-ceph-block-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
status: {}
