apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: jpm-models-data
  name: {{ .Release.Name }}-jpm-models-data
spec:
  storageClassName: rook-ceph-block-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
